# Generated by Django 5.2.3 on 2025-06-27 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_description', models.CharField(max_length=256)),
                ('order_type', models.CharField(choices=[('P', 'Preventive'), ('C', 'Corrective')], max_length=1)),
                ('order_status', models.CharField(choices=[('O', 'Open'), ('I', 'In Progress'), ('C', 'Completed')], max_length=1)),
                ('fk_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_orders', to='machine.machine')),
            ],
        ),
    ]
